<a href="https://colab.research.google.com/github/mattocanas/Makemore/blob/main/Novozyme-Stability-Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("\n... IMPORTS STARTING ...\n")

# Pip installs for competition specific stuff
!pip install -q biopandas
!pip install -q biopython
!pip install tensorflow-addons
!pip install tensorflow-io
!pip install pandarallel
!pip install Levenshtein
!pip install openslide
!pip install kaggle


print("\n\tVERSION INFORMATION")
# Machine Learning and Data Science Imports
import tensorflow as tf; print(f"\t\t– TENSORFLOW VERSION: {tf.__version__}");
import tensorflow_hub as tfhub; print(f"\t\t– TENSORFLOW HUB VERSION: {tfhub.__version__}");
import tensorflow_addons as tfa; print(f"\t\t– TENSORFLOW ADDONS VERSION: {tfa.__version__}");
import tensorflow_io as tfio; print(f"\t\t– TENSORFLOW I/O VERSION: {tfio.__version__}");
import Bio as pyb; print(f"\t\t– BioPython VERSION: {pyb.__version__}");
import biopandas; from biopandas.pdb import PandasPdb; print(f"\t\t– BioPandas VERSION: {biopandas.__version__}"); pdb = PandasPdb();
import pandas as pd; pd.options.mode.chained_assignment = None;
import numpy as np; print(f"\t\t– NUMPY VERSION: {np.__version__}");
import sklearn; print(f"\t\t– SKLEARN VERSION: {sklearn.__version__}");
from sklearn.preprocessing import RobustScaler, PolynomialFeatures
from pandarallel import pandarallel; pandarallel.initialize();
from sklearn.model_selection import GroupKFold, StratifiedKFold
from scipy.spatial import cKDTree

# # RAPIDS
# import cudf, cupy, cuml
# from cuml.neighbors import NearestNeighbors
# from cuml.manifold import TSNE, UMAP
# from cuml import PCA

# Built In Imports
from collections import Counter
from datetime import datetime
from zipfile import ZipFile
from glob import glob
import Levenshtein
# import openslide
import warnings
import requests
import hashlib
import imageio
import IPython
import sklearn
import urllib
import zipfile
import pickle
import random
import shutil
import string
import json
import math
import time
import gzip
import ast
import sys
import io
import os
import gc
import re

# Visualization Imports
from matplotlib.colors import ListedColormap
from matplotlib.patches import Rectangle
import matplotlib.patches as patches
import plotly.graph_objects as go
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm; tqdm.pandas();
import plotly.express as px
import tifffile as tif
import seaborn as sns
from PIL import Image, ImageEnhance; Image.MAX_IMAGE_PIXELS = 5_000_000_000;
import matplotlib; print(f"\t\t– MATPLOTLIB VERSION: {matplotlib.__version__}");
from matplotlib import animation, rc; rc('animation', html='jshtml')
import plotly
import PIL
import cv2

import plotly.io as pio
print(pio.renderers)

def seed_it_all(seed=7):
    """ Attempt to be Reproducible """
    os.environ['PYTHONHASHSEED'] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)

    
print("\n\n... IMPORTS COMPLETE ...\n")

... IMPORTS STARTING ...

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 879.0/879.0 KB 15.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 32.6 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tensorflow-addons
  Downloading tensorflow_addons-0.19.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 15.3 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from tensorflow-addons) (23.0)
Requirement already satisfied: typeguard>=2.7 in /usr/local/lib/python3.8/dist-packages (from tensorflow-addons) (2.7.1)
Installing collected packages: tensorflow-addons
Successfully installed tensorflow-addons-0.19.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tensorflow-io
  Downloading tensorflow_io-0.30.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (26.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.9/26.9 MB 41.1 MB/s eta 0:00:00
Requirement already satisfied: tensorflow-io-gcs-filesystem==0.30.0 in /usr/local/lib/python3.8/dist-packages (from tensorflow-io) (0.30.0)
Installing collected packages: tensorflow-io
Successfully installed tensorflow-io-0.30.0
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pandarallel
  Downloading pandarallel-1.6.4.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: dill>=0.3.1 in /usr/local/lib/python3.8/dist-packages (from pandarallel) (0.3.6)
Requirement already satisfied: pandas>=1 in /usr/local/lib/python3.8/dist-packages (from pandarallel) (1.3.5)
Requirement already satisfied: psutil in /usr/local/lib/python3.8/dist-packages (from pandarallel) (5.4.8)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1->pandarallel) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1->pandarallel) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1->pandarallel) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=1->pandarallel) (1.15.0)
Building wheels for collected packages: pandarallel
  Building wheel for pandarallel (setup.py) ... done
  Created wheel for pandarallel: filename=pandarallel-1.6.4-py3-none-any.whl size=16678 sha256=075860f8c1b19ff388305a5b99060166e66093e83cb54de7ea496729dc62db2d
  Stored in directory: /root/.cache/pip/wheels/62/1e/e7/f9ee096e5cc02890a6934a5670ff6e45a3400f330605bd8210
Successfully built pandarallel
Installing collected packages: pandarallel
Successfully installed pandarallel-1.6.4
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting Levenshtein
  Downloading Levenshtein-0.20.9-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.0/174.0 KB 5.3 MB/s eta 0:00:00
Collecting rapidfuzz<3.0.0,>=2.3.0
  Downloading rapidfuzz-2.13.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 38.8 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, Levenshtein
Successfully installed Levenshtein-0.20.9 rapidfuzz-2.13.7
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
ERROR: Could not find a version that satisfies the requirement openslide (from versions: none)
ERROR: No matching distribution found for openslide
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.8/dist-packages (1.5.12)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from kaggle) (4.64.1)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages (from kaggle) (2.25.1)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.8/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.8/dist-packages (from kaggle) (8.0.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.8/dist-packages (from kaggle) (2022.12.7)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.8/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests->kaggle) (4.0.0)

	VERSION INFORMATION
		– TENSORFLOW VERSION: 2.11.0
		– TENSORFLOW HUB VERSION: 0.12.0
		– TENSORFLOW ADDONS VERSION: 0.19.0
		– TENSORFLOW I/O VERSION: 0.30.0
		– BioPython VERSION: 1.80
		– BioPandas VERSION: 0.4.1
		– NUMPY VERSION: 1.21.6
		– SKLEARN VERSION: 1.0.2
INFO: Pandarallel will run on 1 workers.
INFO: Pandarallel will use Memory file system to transfer data between the main process and workers.
		– MATPLOTLIB VERSION: 3.2.2
Renderers configuration
-----------------------
    Default renderer: 'colab'
    Available renderers:
        ['plotly_mimetype', 'jupyterlab', 'nteract', 'vscode',
         'notebook', 'notebook_connected', 'kaggle', 'azure', 'colab',
         'cocalc', 'databricks', 'json', 'png', 'jpeg', 'jpg', 'svg',
         'pdf', 'browser', 'firefox', 'chrome', 'chromium', 'iframe',
         'iframe_connected', 'sphinx_gallery', 'sphinx_gallery_png']



... IMPORTS COMPLETE ...

In [2]:
print(f"\n... ACCELERATOR SETUP STARTING ...\n")

# Detect hardware, return appropriate distribution strategy
try:
    # TPU detection. No parameters necessary if TPU_NAME environment variable is set. On Kaggle this is always the case.
    TPU = tf.distribute.cluster_resolver.TPUClusterResolver()  
except ValueError:
    TPU = None

if TPU:
    print(f"\n... RUNNING ON TPU - {TPU.master()}...")
    tf.config.experimental_connect_to_cluster(TPU)
    tf.tpu.experimental.initialize_tpu_system(TPU)
    strategy = tf.distribute.experimental.TPUStrategy(TPU)
else:
    print(f"\n... RUNNING ON CPU/GPU ...")
    # Yield the default distribution strategy in Tensorflow
    #   --> Works on CPU and single GPU.
    strategy = tf.distribute.get_strategy()
    _gpus = tf.config.list_physical_devices('GPU')
    if len(_gpus)>0: tf.config.experimental.set_memory_growth([0], True)

# What Is a Replica?
#    --> A single Cloud TPU device consists of FOUR chips, each of which has TWO TPU cores. 
#    --> Therefore, for efficient utilization of Cloud TPU, a program should make use of each of the EIGHT (4x2) cores. 
#    --> Each replica is essentially a copy of the training graph that is run on each core and 
#        trains a mini-batch containing 1/8th of the overall batch size
N_REPLICAS = strategy.num_replicas_in_sync
    
print(f"... # OF REPLICAS: {N_REPLICAS} ...\n")

print(f"\n... ACCELERATOR SETUP COMPLTED ...\n")

... ACCELERATOR SETUP STARTING ...


... RUNNING ON TPU - grpc://10.34.158.82:8470...

WARNING:absl:`tf.distribute.experimental.TPUStrategy` is deprecated, please use  the non experimental symbol `tf.distribute.TPUStrategy` instead.

... # OF REPLICAS: 8 ...


... ACCELERATOR SETUP COMPLTED ...

In [3]:
print(f"\n... XLA OPTIMIZATIONS STARTING ...\n")

print(f"\n... CONFIGURE JIT (JUST IN TIME) COMPILATION ...\n")
# enable XLA optmizations (10% speedup when using @tf.function calls)
tf.config.optimizer.set_jit(True)

print(f"\n... XLA OPTIMIZATIONS COMPLETED ...\n")

... XLA OPTIMIZATIONS STARTING ...


... CONFIGURE JIT (JUST IN TIME) COMPILATION ...


... XLA OPTIMIZATIONS COMPLETED ...

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
# After executing the cell above, Drive
# files will be present in "/content/drive/My Drive".
!ls "/content/drive/My Drive/novozymes-enzyme-stability-prediction 4"

'sample_submission 2.csv'   train.csv
 sample_submission.csv	   'train_updates_20220929 2.csv'
'test 2.csv'		    train_updates_20220929.csv
 test.csv		   'wildtype_structure_prediction_af2 2.pdb'
'train 2.csv'		    wildtype_structure_prediction_af2.pdb

In [6]:
pdb_df =  PandasPdb().read_pdb("/content/drive/My Drive/novozymes-enzyme-stability-prediction 4/wildtype_structure_prediction_af2.pdb")

print(pdb_df.df.keys())
atom_df = pdb_df.df['ATOM']
hetatm_df = pdb_df.df['HETATM']
anisou_df = pdb_df.df['ANISOU']
others_df = pdb_df.df['OTHERS']

dict_keys(['ATOM', 'HETATM', 'ANISOU', 'OTHERS'])

In [7]:
print("\n... BASIC DATA SETUP STARTING ...\n")

print("\n\n... LOAD TRAIN DATAFRAME FROM CSV FILE ...\n")
train_df = pd.read_csv("/content/drive/My Drive/novozymes-enzyme-stability-prediction 4/train.csv")
display(train_df)

print("\n\n... LOAD TEST DATAFRAME FROM CSV FILE ...\n")
test_df = pd.read_csv("/content/drive/My Drive/novozymes-enzyme-stability-prediction 4/test.csv")
display(test_df)

print("\n\n... LOAD SAMPLE SUBMISSION DATAFRAME FROM CSV FILE ...\n")
ss_df = pd.read_csv("/content/drive/My Drive/novozymes-enzyme-stability-prediction 4/sample_submission.csv")
display(ss_df)

print("\n\n... LOAD ALPHAFOLD WILDTYPE STRUCTURE DATA FROM PDB FILE ...\n")
pdb_df = pdb.read_pdb("/content/drive/My Drive/novozymes-enzyme-stability-prediction 4/wildtype_structure_prediction_af2.pdb")

print("ATOM DATA...")
atom_df   = pdb_df.df['ATOM']
display(atom_df)

print("\nHETATM DATA...")
hetatm_df = pdb_df.df['HETATM']
display(hetatm_df)

print("\nANISOU DATA...")
anisou_df = pdb_df.df['ANISOU']
display(anisou_df)

print("\nOTHERS DATA...")
others_df = pdb_df.df['OTHERS']
display(others_df)

... BASIC DATA SETUP STARTING ...



... LOAD TRAIN DATAFRAME FROM CSV FILE ...

,seq_id,protein_sequence,pH,data_source,tm
0,0,AAAAKAAALALLGEAPEVVDIWLPAGWRQPFRVFRLERKGDGVLVG...,7.0,doi.org/10.1038/s41592-020-0801-4,75.7
1,1,AAADGEPLHNEEERAGAGQVGRSLPQESEEQRTGSRPRRRRDLGSR...,7.0,doi.org/10.1038/s41592-020-0801-4,50.5
2,2,AAAFSTPRATSYRILSSAGSGSTRADAPQVRRLHTTRDLLAKDYYA...,7.0,doi.org/10.1038/s41592-020-0801-4,40.5
3,3,AAASGLRTAIPAQPLRHLLQPAPRPCLRPFGLLSVRAGSARRSGLL...,7.0,doi.org/10.1038/s41592-020-0801-4,47.2
4,4,AAATKSGPRRQSQGASVRTFTPFYFLVEPVDTLSVRGSSVILNCSA...,7.0,doi.org/10.1038/s41592-020-0801-4,49.5
...,...,...,...,...,...
31385,31385,YYMYSGGGSALAAGGGGAGRKGDWNDIDSIKKKDLHHSRGDEKAQG...,7.0,doi.org/10.1038/s41592-020-0801-4,51.8
31386,31386,YYNDQHRLSSYSVETAMFLSWERAIVKPGAMFKKAVIGFNCNVDLI...,7.0,doi.org/10.1038/s41592-020-0801-4,37.2
31387,31387,YYQRTLGAELLYKISFGEMPKSAQDSAENCPSGMQFPDTAIAHANV...,7.0,doi.org/10.1038/s41592-020-0801-4,64.6
31388,31388,YYSFSDNITTVFLSRQAIDDDHSLSLGTISDVVESENGVVAADDAR...,7.0,doi.org/10.1038/s41592-020-0801-4,50.7
31389,31389,YYVPDEYWQSLEVAHKLTFGYGYLTWEWVQGIRSYVYPLLIAGLYK...,7.0,doi.org/10.1038/s41592-020-0801-4,37.6

... LOAD TEST DATAFRAME FROM CSV FILE ...

,seq_id,protein_sequence,pH,data_source
0,31390,VPVNPEPDATSVENVAEKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes
1,31391,VPVNPEPDATSVENVAKKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes
2,31392,VPVNPEPDATSVENVAKTGSGDSQSDPIKADLEVKGQSALPFDVDC...,8,Novozymes
3,31393,VPVNPEPDATSVENVALCTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes
4,31394,VPVNPEPDATSVENVALFTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes
...,...,...,...,...
2408,33798,VPVNPEPDATSVENVILKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes
2409,33799,VPVNPEPDATSVENVLLKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes
2410,33800,VPVNPEPDATSVENVNLKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes
2411,33801,VPVNPEPDATSVENVPLKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes
2412,33802,VPVNPEPDATSVENVWLKTGSGDSQSDPIKADLEVKGQSALPFDVD...,8,Novozymes

... LOAD SAMPLE SUBMISSION DATAFRAME FROM CSV FILE ...

      seq_id    tm
0      31390     0
1      31391     1
2      31392     2
3      31393     3
4      31394     4
...      ...   ...
2408   33798  2408
2409   33799  2409
2410   33800  2410
2411   33801  2411
2412   33802  2412

[2413 rows x 2 columns]

... LOAD ALPHAFOLD WILDTYPE STRUCTURE DATA FROM PDB FILE ...

ATOM DATA...

,record_name,atom_number,blank_1,atom_name,alt_loc,residue_name,blank_2,chain_id,residue_number,insertion,...,x_coord,y_coord,z_coord,occupancy,b_factor,blank_4,segment_id,element_symbol,charge,line_idx
0,ATOM,1,,N,,VAL,,A,1,,...,34.064,-6.456,50.464,1.0,45.11,,,N,NaN,0
1,ATOM,2,,H,,VAL,,A,1,,...,33.576,-6.009,51.228,1.0,45.11,,,H,NaN,1
2,ATOM,3,,H2,,VAL,,A,1,,...,33.882,-7.449,50.477,1.0,45.11,,,H,NaN,2
3,ATOM,4,,H3,,VAL,,A,1,,...,35.060,-6.323,50.566,1.0,45.11,,,H,NaN,3
4,ATOM,5,,CA,,VAL,,A,1,,...,33.643,-5.877,49.162,1.0,45.11,,,C,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3312,ATOM,3313,,NZ,,LYS,,A,221,,...,4.616,13.323,-4.301,1.0,93.80,,,N,NaN,3312
3313,ATOM,3314,,HZ1,,LYS,,A,221,,...,5.270,12.565,-4.432,1.0,93.80,,,H,NaN,3313
3314,ATOM,3315,,HZ2,,LYS,,A,221,,...,4.585,13.517,-3.310,1.0,93.80,,,H,NaN,3314
3315,ATOM,3316,,HZ3,,LYS,,A,221,,...,4.965,14.143,-4.776,1.0,93.80,,,H,NaN,3315
3316,ATOM,3317,,OXT,,LYS,,A,221,,...,1.511,13.763,-11.203,1.0,93.80,,,O,NaN,3316

HETATM DATA...

Empty DataFrame
Columns: [record_name, atom_number, blank_1, atom_name, alt_loc, residue_name, blank_2, chain_id, residue_number, insertion, blank_3, x_coord, y_coord, z_coord, occupancy, b_factor, blank_4, segment_id, element_symbol, charge, line_idx]
Index: []

[0 rows x 21 columns]

ANISOU DATA...

Empty DataFrame
Columns: [record_name, atom_number, blank_1, atom_name, alt_loc, residue_name, blank_2, chain_id, residue_number, insertion, blank_3, U(1,1), U(2,2), U(3,3), U(1,2), U(1,3), U(2,3), blank_4, element_symbol, charge, line_idx]
Index: []

[0 rows x 21 columns]

OTHERS DATA...

  record_name                 entry  line_idx
0         TER   3318      LYS A 221      3317
1         END                            3318

* Atom serial number: This is a unique identifier assigned to each atom in the structure. It is a sequential number assigned to each atom in the order they appear in the PDB file.

* Atom name: This is the name of the atom, which can be either a standard element symbol or a standard element symbol followed by a number to distinguish different atoms of the same element in the same residue.

* Alternate location indicator: This field is used to indicate the presence of alternative positions for an atom within a residue. If an atom has multiple positions, each will be given a unique alternate location identifier.

* Residue name: This is the name of the residue to which the atom belongs. Residues are the building blocks of proteins or nucleic acids and are typically composed of one or more atoms.

* Chain identifier: This is a single letter code used to identify the chain in which the residue is located.

* Residue sequence number: This is a unique identifier for the residue, assigned based on its position within the chain.

* Code for insertion of residues: This field is used to specify the presence of inserted residues, which are residues that have been added to the structure after its initial formation.

* Orthogonal coordinates for X, Y, and Z in Angstroms: These are the 3D coordinates of the atom in space, given in Angstroms. X, Y, and Z define the position of the atom relative to a fixed point in space.

* Occupancy: This is a value that indicates the fraction of the time the atom is found at its defined position in the crystal structure.

* **Temperature factor (also known as B factor): This is a measure of the thermal motion of the atom, given in Angstroms^2. A high B factor indicates high thermal motion and a low B factor indicates low thermal motion.**
  * a high B factor indicates that an atom deviates more from its ideal conformation due to a change (increase) in temperature
  * this can alter the stability or activity of an enzyme

* Element symbol: This is the standard symbol for the chemical element to which the atom belongs, such as C for carbon or N for nitrogen.

* Charge on the atom: This field is used to indicate the charge on the atom, if any. In most cases, atoms in proteins or nucleic acids are neutral and have a charge of zero.*

In [14]:
print("\n\n... SAVING WILDTYPE AMINO ACID SEQUENCE...\n")
wildtype_aa = "VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVDCWAILCKGAPNVLQRVNEKTKNSNRDRSGANKGPFKDPQKWGIKALPPKNPSWSAQDFKSPEEYAFASSLQGGTNAILAPVNLASQNSQGGVLNGFYSANKVAQFDPSKPQQTKGTWFQITKFTGAAGPYCKALGSNDKSVCDKNKNIAGDWGFDPAKWAYQYDEKNNKFNYVGK"
print(wildtype_aa)

print("\n\n... DEFINE AMINO ACID SHORTFORM DICTIONARY MAPPING...\n")
aa_map = dict(Alanine=("Ala", "A"), Arginine=("Arg", "R"), Asparagine=("Asn", "N"), Aspartic_Acid=("Asp", "D"),
              Cysteine=("Cys", "C"), Glutamic_Acid=("Glu", "E"), Glutamine=("Gln", "Q"), Glycine=("Gly", "G"),
              Histidine=("His", "H"), Isoleucine=("Ile", "I"), Leucine=("Leu", "L"), Lysine=("Lys", "K"),
              Methionine=("Met", "M"), Phenylalanine=("Phe", "F"), Proline=("Pro", "P"), Serine=("Ser", "S"),
              Threonine=("Thr", "T"), Tryptophan=("Trp", "W"), Tyrosine=("Tyr", "Y"), Valine=("Val", "V"))
n_aa = len(aa_map)
aa_chars_ordered = sorted([v[1] for v in aa_map.values()])
aa_long2tri = {k:v[0] for k,v in aa_map.items()} # map full name to 3-letter code
aa_long2char = {k:v[1] for k,v in aa_map.items()} # map full name to single-letter code
aa_tri2long = {v:k for k,v in aa_long2tri.items()} # map 3-letter code to full name
aa_char2long = {v:k for k,v in aa_long2char.items()} # map 1 letter code to full name
aa_char2int = {_aa:i for i, _aa in enumerate(aa_chars_ordered)} # map single letter code to number
aa_int2char = {v:k for k,v in aa_char2int.items()} # map number to single letter code

... SAVING WILDTYPE AMINO ACID SEQUENCE...

VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVDCWAILCKGAPNVLQRVNEKTKNSNRDRSGANKGPFKDPQKWGIKALPPKNPSWSAQDFKSPEEYAFASSLQGGTNAILAPVNLASQNSQGGVLNGFYSANKVAQFDPSKPQQTKGTWFQITKFTGAAGPYCKALGSNDKSVCDKNKNIAGDWGFDPAKWAYQYDEKNNKFNYVGK


... DEFINE AMINO ACID SHORTFORM DICTIONARY MAPPING...

In [20]:
# Get data source map
print("\n\n... DEFINE DATASOURCE DICTIONARY MAPPING...\n")

# map each uniqe data source in the training set to an integer. then do the reverse, mapping each integer to each unique data source in the training set
ds_str2int = {k:i for i,k in enumerate(train_df["data_source"].unique())}
ds_int2str = {v:k for k,v in ds_str2int.items()}

... DEFINE DATASOURCE DICTIONARY MAPPING...

In [22]:
for k,v in aa_map.items(): print(f"'{k}':\n\t3 LETTER ABBREVIATION --> '{v[0]}'\n\t1 LETTER ABBREVIATION --> '{v[1]}'\n")

'Alanine':
	3 LETTER ABBREVIATION --> 'Ala'
	1 LETTER ABBREVIATION --> 'A'

'Arginine':
	3 LETTER ABBREVIATION --> 'Arg'
	1 LETTER ABBREVIATION --> 'R'

'Asparagine':
	3 LETTER ABBREVIATION --> 'Asn'
	1 LETTER ABBREVIATION --> 'N'

'Aspartic_Acid':
	3 LETTER ABBREVIATION --> 'Asp'
	1 LETTER ABBREVIATION --> 'D'

'Cysteine':
	3 LETTER ABBREVIATION --> 'Cys'
	1 LETTER ABBREVIATION --> 'C'

'Glutamic_Acid':
	3 LETTER ABBREVIATION --> 'Glu'
	1 LETTER ABBREVIATION --> 'E'

'Glutamine':
	3 LETTER ABBREVIATION --> 'Gln'
	1 LETTER ABBREVIATION --> 'Q'

'Glycine':
	3 LETTER ABBREVIATION --> 'Gly'
	1 LETTER ABBREVIATION --> 'G'

'Histidine':
	3 LETTER ABBREVIATION --> 'His'
	1 LETTER ABBREVIATION --> 'H'

'Isoleucine':
	3 LETTER ABBREVIATION --> 'Ile'
	1 LETTER ABBREVIATION --> 'I'

'Leucine':
	3 LETTER ABBREVIATION --> 'Leu'
	1 LETTER ABBREVIATION --> 'L'

'Lysine':
	3 LETTER ABBREVIATION --> 'Lys'
	1 LETTER ABBREVIATION --> 'K'

'Methionine':
	3 LETTER ABBREVIATION --> 'Met'
	1 LETTER ABBREVIATION --> 'M'

'Phenylalanine':
	3 LETTER ABBREVIATION --> 'Phe'
	1 LETTER ABBREVIATION --> 'F'

'Proline':
	3 LETTER ABBREVIATION --> 'Pro'
	1 LETTER ABBREVIATION --> 'P'

'Serine':
	3 LETTER ABBREVIATION --> 'Ser'
	1 LETTER ABBREVIATION --> 'S'

'Threonine':
	3 LETTER ABBREVIATION --> 'Thr'
	1 LETTER ABBREVIATION --> 'T'

'Tryptophan':
	3 LETTER ABBREVIATION --> 'Trp'
	1 LETTER ABBREVIATION --> 'W'

'Tyrosine':
	3 LETTER ABBREVIATION --> 'Tyr'
	1 LETTER ABBREVIATION --> 'Y'

'Valine':
	3 LETTER ABBREVIATION --> 'Val'
	1 LETTER ABBREVIATION --> 'V'

In [23]:
print("\n\n... FOR FUN ... HERE IS THE ENTIRE WILDTYPE WITH FULL AMINO ACID NAMES (8 AA PER LINE) ...\n")
for i, _c in enumerate(wildtype_aa): print(f"'{aa_char2long[_c]}'", end=", ") if (i+1)%8!=0 else print(f"{aa_char2long[_c]}", end=",\n")

... FOR FUN ... HERE IS THE ENTIRE WILDTYPE WITH FULL AMINO ACID NAMES (8 AA PER LINE) ...

'Valine', 'Proline', 'Valine', 'Asparagine', 'Proline', 'Glutamic_Acid', 'Proline', Aspartic_Acid,
'Alanine', 'Threonine', 'Serine', 'Valine', 'Glutamic_Acid', 'Asparagine', 'Valine', Alanine,
'Leucine', 'Lysine', 'Threonine', 'Glycine', 'Serine', 'Glycine', 'Aspartic_Acid', Serine,
'Glutamine', 'Serine', 'Aspartic_Acid', 'Proline', 'Isoleucine', 'Lysine', 'Alanine', Aspartic_Acid,
'Leucine', 'Glutamic_Acid', 'Valine', 'Lysine', 'Glycine', 'Glutamine', 'Serine', Alanine,
'Leucine', 'Proline', 'Phenylalanine', 'Aspartic_Acid', 'Valine', 'Aspartic_Acid', 'Cysteine', Tryptophan,
'Alanine', 'Isoleucine', 'Leucine', 'Cysteine', 'Lysine', 'Glycine', 'Alanine', Proline,
'Asparagine', 'Valine', 'Leucine', 'Glutamine', 'Arginine', 'Valine', 'Asparagine', Glutamic_Acid,
'Lysine', 'Threonine', 'Lysine', 'Asparagine', 'Serine', 'Asparagine', 'Arginine', Aspartic_Acid,
'Arginine', 'Serine', 'Glycine', 'Alanine', 'Asparagine', 'Lysine', 'Glycine', Proline,
'Phenylalanine', 'Lysine', 'Aspartic_Acid', 'Proline', 'Glutamine', 'Lysine', 'Tryptophan', Glycine,
'Isoleucine', 'Lysine', 'Alanine', 'Leucine', 'Proline', 'Proline', 'Lysine', Asparagine,
'Proline', 'Serine', 'Tryptophan', 'Serine', 'Alanine', 'Glutamine', 'Aspartic_Acid', Phenylalanine,
'Lysine', 'Serine', 'Proline', 'Glutamic_Acid', 'Glutamic_Acid', 'Tyrosine', 'Alanine', Phenylalanine,
'Alanine', 'Serine', 'Serine', 'Leucine', 'Glutamine', 'Glycine', 'Glycine', Threonine,
'Asparagine', 'Alanine', 'Isoleucine', 'Leucine', 'Alanine', 'Proline', 'Valine', Asparagine,
'Leucine', 'Alanine', 'Serine', 'Glutamine', 'Asparagine', 'Serine', 'Glutamine', Glycine,
'Glycine', 'Valine', 'Leucine', 'Asparagine', 'Glycine', 'Phenylalanine', 'Tyrosine', Serine,
'Alanine', 'Asparagine', 'Lysine', 'Valine', 'Alanine', 'Glutamine', 'Phenylalanine', Aspartic_Acid,
'Proline', 'Serine', 'Lysine', 'Proline', 'Glutamine', 'Glutamine', 'Threonine', Lysine,
'Glycine', 'Threonine', 'Tryptophan', 'Phenylalanine', 'Glutamine', 'Isoleucine', 'Threonine', Lysine,
'Phenylalanine', 'Threonine', 'Glycine', 'Alanine', 'Alanine', 'Glycine', 'Proline', Tyrosine,
'Cysteine', 'Lysine', 'Alanine', 'Leucine', 'Glycine', 'Serine', 'Asparagine', Aspartic_Acid,
'Lysine', 'Serine', 'Valine', 'Cysteine', 'Aspartic_Acid', 'Lysine', 'Asparagine', Lysine,
'Asparagine', 'Isoleucine', 'Alanine', 'Glycine', 'Aspartic_Acid', 'Tryptophan', 'Glycine', Phenylalanine,
'Aspartic_Acid', 'Proline', 'Alanine', 'Lysine', 'Tryptophan', 'Alanine', 'Tyrosine', Glutamine,
'Tyrosine', 'Aspartic_Acid', 'Glutamic_Acid', 'Lysine', 'Asparagine', 'Asparagine', 'Lysine', Phenylalanine,
'Asparagine', 'Tyrosine', 'Valine', 'Glycine', 'Lysine',

In [24]:
print("\n\n... ADD COLUMNS FOR PROTEIN SEQUENCE LENGTH AND INDIVIDUAL AMINO ACID COUNTS/FRACTIONS ...\n")
train_df["n_AA"] = train_df["protein_sequence"].apply(len)
test_df["n_AA"] = test_df["protein_sequence"].apply(len)
for _aa_char in aa_chars_ordered: 
    train_df[f"AA_{_aa_char}__count"] = train_df["protein_sequence"].apply(lambda x: x.count(_aa_char))
    train_df[f"AA_{_aa_char}__fraction"] = train_df[f"AA_{_aa_char}__count"]/train_df["n_AA"]
    test_df[f"AA_{_aa_char}__count"] = test_df["protein_sequence"].apply(lambda x: x.count(_aa_char))
    test_df[f"AA_{_aa_char}__fraction"] = test_df[f"AA_{_aa_char}__count"]/test_df["n_AA"]

... ADD COLUMNS FOR PROTEIN SEQUENCE LENGTH AND INDIVIDUAL AMINO ACID COUNTS/FRACTIONS ...

In [25]:
print("\n... ADD COLUMNS FOR DATA SOURCE ENUMERATION ...\n")
train_df["data_source_enum"] = train_df['data_source'].map(ds_str2int)
test_df["data_source_enum"] = test_df['data_source'].map(ds_str2int)

... ADD COLUMNS FOR DATA SOURCE ENUMERATION ...

In [26]:
# if pH > 14, it is likely just an accidental swap between tm and pH value because there cannot be pH >14. so swap them around
print("\n... DO TEMPORARY pH FIX BY SWAPPING pH & tm IF pH>14 ...\n")
def tmp_ph_fix(_row):
    if _row["pH"]>14:
        print(f"\t--> pH WEIRDNESS EXISTS AT INDEX {_row.name}")
        _tmp = _row["pH"]
        _row["pH"] = _row["tm"]
        _row["tm"] = _tmp
        return _row
    else:
        return _row

print(f"\t--> DOES THE  STILL EXIST: {train_df['pH'].max()>14.0}")
train_df = train_df.progress_apply(tmp_ph_fix, axis=1)
test_df = test_df.progress_apply(tmp_ph_fix, axis=1)
    
print("\n\n\n... BASIC DATA SETUP FINISHED ...\n\n")

... DO TEMPORARY pH FIX BY SWAPPING pH & tm IF pH>14 ...

	--> DOES THE  STILL EXIST: True

  0%|          | 0/31390 [00:00<?, ?it/s]

	--> pH WEIRDNESS EXISTS AT INDEX 973
	--> pH WEIRDNESS EXISTS AT INDEX 986
	--> pH WEIRDNESS EXISTS AT INDEX 988
	--> pH WEIRDNESS EXISTS AT INDEX 989
	--> pH WEIRDNESS EXISTS AT INDEX 1003
	--> pH WEIRDNESS EXISTS AT INDEX 1012
	--> pH WEIRDNESS EXISTS AT INDEX 1014
	--> pH WEIRDNESS EXISTS AT INDEX 1018
	--> pH WEIRDNESS EXISTS AT INDEX 1037
	--> pH WEIRDNESS EXISTS AT INDEX 1042
	--> pH WEIRDNESS EXISTS AT INDEX 1079
	--> pH WEIRDNESS EXISTS AT INDEX 1081
	--> pH WEIRDNESS EXISTS AT INDEX 1088
	--> pH WEIRDNESS EXISTS AT INDEX 1093
	--> pH WEIRDNESS EXISTS AT INDEX 1096
	--> pH WEIRDNESS EXISTS AT INDEX 1098
	--> pH WEIRDNESS EXISTS AT INDEX 1100
	--> pH WEIRDNESS EXISTS AT INDEX 1108
	--> pH WEIRDNESS EXISTS AT INDEX 1111
	--> pH WEIRDNESS EXISTS AT INDEX 1120
	--> pH WEIRDNESS EXISTS AT INDEX 1122
	--> pH WEIRDNESS EXISTS AT INDEX 1125
	--> pH WEIRDNESS EXISTS AT INDEX 13447
	--> pH WEIRDNESS EXISTS AT INDEX 13449
	--> pH WEIRDNESS EXISTS AT INDEX 14640
	--> pH WEIRDNESS EXISTS AT INDEX 22116
	--> pH WEIRDNESS EXISTS AT INDEX 22123
	--> pH WEIRDNESS EXISTS AT INDEX 22131
	--> pH WEIRDNESS EXISTS AT INDEX 22145

  0%|          | 0/2413 [00:00<?, ?it/s]

... BASIC DATA SETUP FINISHED ...

## Helper Functions and Classes Below

Sets the wildtype sequence and takes a dictionary that contains an amino acid sequence.

Sets the terminology map. Levenshtein returns "replace", "insert", and "delete". In biological mutation terms, there are: "substitution", "insertion", "deletion".

Use Levenshetin.editops() to find all the operations needed to change the input sequence to the wild tpye. Accoding to chatgpt, this is how levenshetin works:


```
s1 = "apple"
s2 = "banana"
editops = Levenshtein.editops(s1, s2)
editops
----
[('replace', 0, 0), ('insert', 3, 4), ('replace', 4, 5), ('replace', 5, 6)]
```
This output shows that the first operation to turn s2 to s1 is to replace the 0th index. then make an insertion at the 3rd index of s2. The value to be inserted there can be found at the 4th index of s1.


If no len(req_edits) == 0. then there are no edits to be made. essentially, the input sequence is the same as the wildtype. so all the value are set to pd.NA

If there are edits to be made:
* find what kind of edit (the terminology)
* find the index that edit should occur at 
* find what the wild type amino acid is at that index
* find what the mutant amino acid is. if it is a deletion. set this to pd.NA

In [27]:
def get_mutation_info(_row, _wildtype="VPVNPEPDATSVENVALKTGSGDSQSDPIKADLEVKGQSALPFDVDCWAILCKGAPNVLQ" \
                                      "RVNEKTKNSNRDRSGANKGPFKDPQKWGIKALPPKNPSWSAQDFKSPEEYAFASSLQGGT" \
                                      "NAILAPVNLASQNSQGGVLNGFYSANKVAQFDPSKPQQTKGTWFQITKFTGAAGPYCKAL" \
                                      "GSNDKSVCDKNKNIAGDWGFDPAKWAYQYDEKNNKFNYVGK"):
    terminology_map = {"replace":"substitution", "insert":"insertion", "delete":"deletion"}
    req_edits = Levenshtein.editops(_wildtype, _row["protein_sequence"])
    _row["n_edits"] = len(req_edits)
    
    if _row["n_edits"]==0:
        _row["edit_type"] = _row["edit_idx"] = _row["wildtype_aa"] = _row["mutant_aa"] = pd.NA
    else:
        _row["edit_type"] = terminology_map[req_edits[0][0]]
        _row["edit_idx"] = req_edits[0][1]
        _row["wildtype_aa"] = _wildtype[_row["edit_idx"]]
        _row["mutant_aa"] = _row["protein_sequence"][req_edits[0][2]] if _row["edit_type"]!="deletion" else pd.NA
    return _row

Checks to see if there is actually a difference between input and wildtype.. If not, the sequence is returned unaltered.

If the type of edit is not an insertion (replacement or deletion):
* creat a base that is the protein sequence up until the index that is edited.
* if it is a deletion, take the new base, add the wildtype amino acid, add the rest of the sequence until the end
* if it is a replacement, make the new wildtype equal to the base plus the wildtype AA plus the rest of the protein sequence, but skipping the AA at the replacement point
* Finally, if the edit type is an insertion. set the new wild_type equal to the protein sequence up until the edit, plus the wild type AA, plus the rest of the sequence

In [28]:
def revert_to_wildtype(protein_sequence, edit_type, edit_idx, wildtype_aa, mutant_aa):
    if pd.isna(edit_type):
        return protein_sequence
    elif edit_type!="insertion":
        new_wildtype_base = protein_sequence[:edit_idx]
        if edit_type=="deletion":
            new_wildtype=new_wildtype_base+wildtype_aa+protein_sequence[edit_idx:]
        else:
            new_wildtype=new_wildtype_base+wildtype_aa+protein_sequence[edit_idx+1:]
    else:
        new_wildtype=protein_sequence[:edit_idx]+wildtype_aa+protein_sequence[edit_idx:]
    return new_wildtype

The code below turns a list of lists into one big list.

Then there is a function that just prints a line of 110 characters

In [29]:
def flatten_l_o_l(nested_list):
    """ Flatten a list of lists """
    return [item for sublist in nested_list for item in sublist]

def print_ln(symbol="-", line_len=110):
    print(symbol*line_len)

## Training Set Exploration

In [30]:
# Get number of training examples
n_train = len(train_df)

print("\n... DATAFRAME INFO ...\n")
train_df.info()

print("\n\n\n... RELEVANT DATAFRAME COLUMN DESCRIPTIONS ...\n")
display(train_df.describe().T)

... DATAFRAME INFO ...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31390 entries, 0 to 31389
Data columns (total 47 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   seq_id            31390 non-null  int64
 1   protein_sequence  31390 non-null  object
 2   pH                31104 non-null  float64
 3   data_source       28043 non-null  object
 4   tm                31390 non-null  float64
 5   n_AA              31390 non-null  int64
 6   AA_A__count       31390 non-null  int64
 7   AA_A__fraction    31390 non-null  float64
 8   AA_C__count       31390 non-null  int64
 9   AA_C__fraction    31390 non-null  float64
 10  AA_D__count       31390 non-null  int64
 11  AA_D__fraction    31390 non-null  float64
 12  AA_E__count       31390 non-null  int64
 13  AA_E__fraction    31390 non-null  float64
 14  AA_F__count       31390 non-null  int64
 15  AA_F__fraction    31390 non-null  float64
 16  AA_G__count       31390 non-null  int64
 17  AA_G__fraction    31390 non-null  float64
 18  AA_H__count       31390 non-null  int64
 19  AA_H__fraction    31390 non-null  float64
 20  AA_I__count       31390 non-null  int64
 21  AA_I__fraction    31390 non-null  float64
 22  AA_K__count       31390 non-null  int64
 23  AA_K__fraction    31390 non-null  float64
 24  AA_L__count       31390 non-null  int64
 25  AA_L__fraction    31390 non-null  float64
 26  AA_M__count       31390 non-null  int64
 27  AA_M__fraction    31390 non-null  float64
 28  AA_N__count       31390 non-null  int64
 29  AA_N__fraction    31390 non-null  float64
 30  AA_P__count       31390 non-null  int64
 31  AA_P__fraction    31390 non-null  float64
 32  AA_Q__count       31390 non-null  int64
 33  AA_Q__fraction    31390 non-null  float64
 34  AA_R__count       31390 non-null  int64
 35  AA_R__fraction    31390 non-null  float64
 36  AA_S__count       31390 non-null  int64
 37  AA_S__fraction    31390 non-null  float64
 38  AA_T__count       31390 non-null  int64
 39  AA_T__fraction    31390 non-null  float64
 40  AA_V__count       31390 non-null  int64
 41  AA_V__fraction    31390 non-null  float64
 42  AA_W__count       31390 non-null  int64
 43  AA_W__fraction    31390 non-null  float64
 44  AA_Y__count       31390 non-null  int64
 45  AA_Y__fraction    31390 non-null  float64
 46  data_source_enum  31390 non-null  int64
dtypes: float64(22), int64(23), object(2)
memory usage: 11.3+ MB



... RELEVANT DATAFRAME COLUMN DESCRIPTIONS ...

,count,mean,std,min,25%,50%,75%,max
seq_id,31390.0,15694.500000,9061.656811,0.0,7847.250000,15694.500000,23541.750000,31389.000000
pH,31104.0,6.849342,0.865250,0.0,7.000000,7.000000,7.000000,11.000000
tm,31390.0,49.189943,13.946754,-1.0,42.100000,48.000000,53.800000,130.000000
n_AA,31390.0,447.669513,640.728935,5.0,197.000000,336.000000,523.000000,32767.000000
AA_A__count,31390.0,34.297579,43.774015,0.0,15.000000,26.000000,43.000000,1989.000000
AA_A__fraction,31390.0,0.079204,0.028294,0.0,0.059281,0.076479,0.094862,0.298658
AA_C__count,31390.0,6.605607,12.763594,0.0,2.000000,4.000000,8.000000,498.000000
AA_C__fraction,31390.0,0.014694,0.013378,0.0,0.006369,0.012195,0.019355,0.160714
AA_D__count,31390.0,24.880280,35.269664,0.0,10.000000,18.000000,30.000000,1660.000000
AA_D__fraction,31390.0,0.055320,0.017783,0.0,0.043780,0.054299,0.064877,0.205298
AA_E__count,31390.0,32.600287,57.679459,0.0,12.000000,22.000000,39.000000,3027.000000
AA_E__fraction,31390.0,0.070239,0.025211,0.0,0.054203,0.068302,0.083828,0.246575
AA_F__count,31390.0,16.581809,19.920559,0.0,7.000000,12.000000,21.000000,867.000000
AA_F__fraction,31390.0,0.037670,0.014933,0.0,0.028554,0.036199,0.045673,0.154930
AA_G__count,31390.0,29.935553,40.582578,0.0,13.000000,22.000000,37.000000,2004.000000
AA_G__fraction,31390.0,0.069822,0.025274,0.0,0.053685,0.067073,0.083867,0.609195
AA_H__count,31390.0,10.060401,13.070886,0.0,4.000000,7.000000,13.000000,448.000000
AA_H__fraction,31390.0,0.021650,0.011512,0.0,0.014118,0.020833,0.028169,0.146341
AA_I__count,31390.0,23.767729,36.585481,0.0,10.000000,18.000000,30.000000,1982.000000
AA_I__fraction,31390.0,0.054705,0.021710,0.0,0.041152,0.053640,0.067073,0.229050
AA_K__count,31390.0,28.200287,50.205514,0.0,12.000000,20.000000,33.000000,2811.000000
AA_K__fraction,31390.0,0.065135,0.027547,0.0,0.046309,0.062687,0.079268,0.290456
AA_L__count,31390.0,41.966550,52.262031,0.0,17.000000,31.000000,50.000000,2016.000000
AA_L__fraction,31390.0,0.093147,0.026736,0.0,0.076453,0.091109,0.106825,0.281501
AA_M__count,31390.0,10.306021,11.179000,0.0,4.000000,8.000000,13.000000,367.000000
AA_M__fraction,31390.0,0.024420,0.011029,0.0,0.017161,0.023810,0.030488,0.141026
AA_N__count,31390.0,18.847021,25.158768,0.0,8.000000,13.000000,22.000000,1081.000000
AA_N__fraction,31390.0,0.042604,0.018434,0.0,0.030612,0.041045,0.052632,0.319899
AA_P__count,31390.0,22.532431,44.987207,0.0,7.000000,15.000000,26.000000,2439.000000
AA_P__fraction,31390.0,0.046567,0.021822,0.0,0.032258,0.044543,0.057213,0.269461
AA_Q__count,31390.0,19.437623,28.756956,0.0,7.000000,12.000000,22.000000,870.000000
AA_Q__fraction,31390.0,0.040669,0.018765,0.0,0.029412,0.038243,0.050147,0.243464
AA_R__count,31390.0,23.757662,33.269851,0.0,9.000000,17.000000,29.000000,1532.000000
AA_R__fraction,31390.0,0.053622,0.022516,0.0,0.038808,0.051484,0.065502,0.245399
AA_S__count,31390.0,32.176521,50.387319,0.0,11.000000,21.000000,37.000000,2268.000000
AA_S__fraction,31390.0,0.066977,0.025466,0.0,0.048488,0.064748,0.082251,0.357143
AA_T__count,31390.0,24.176649,43.938906,0.0,10.000000,17.000000,29.000000,2416.000000
AA_T__fraction,31390.0,0.053332,0.017667,0.0,0.041835,0.052478,0.063712,0.256198
AA_V__count,31390.0,29.247372,53.060187,0.0,13.000000,22.000000,35.000000,3091.000000
AA_V__fraction,31390.0,0.067034,0.020324,0.0,0.054015,0.065657,0.078904,0.285714
AA_W__count,31390.0,5.025613,8.888754,0.0,1.000000,3.000000,6.000000,456.000000
AA_W__fraction,31390.0,0.011795,0.009196,0.0,0.005057,0.009921,0.016807,0.080460
AA_Y__count,31390.0,13.266518,18.562705,0.0,6.000000,10.000000,17.000000,948.000000
AA_Y__fraction,31390.0,0.031395,0.014311,0.0,0.021448,0.030303,0.039683,0.123180
data_source_enum,31390.0,19.505384,62.807273,0.0,0.000000,0.000000,0.000000,324.000000